version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      image: welyo-recruitment:0.0.1
    ports:
      - "8080:8080"
    environment:
      - SERVER_HELLO=Hello, World!
      - PORT=8080
    restart: always